metanorma_name: generic
organization_name_short: MBx-IF
organization_name_long: Model-Based "x" Interoperability Forum
document_namespace: https://open.ribose.com/standards/mbx-if
xml_root_tag: 'mbxif-standard'
#logo_path: /metanorma-mine/lib/isodoc/mine/html/logo.jpg
#logo_paths: 
#- /metanorma-mine/lib/isodoc/mine/html/logo1.jpg
#- /metanorma-mine/lib/isodoc/mine/html/logo2.jpg
#validate_rng_file: /metanorma-mine/lib/metanorma/mine/mine.rng
htmlcoverpage: html/html_mbxif_titlepage.html
htmlintropage: html/html_mbxif_intro.html
htmlstylesheet: html/htmlstyle.scss
html_bodyfont: '"Source Sans Pro",sans-serif'
html_headerfont: '"Source Sans Pro",sans-serif'
html_monospacefont: '"Source Code Pro",monospace'
html_normalfontsize: "1.0em"
html_monospacefontsize: "0.8em"
html_smallerfontsize: "0.9em"
html_footnotefontsize: "0.8em"
#scripts: /metanorma-mine/lib/isodoc/mine/html/scripts.html
#scripts_pdf: /metanorma-mine/lib/isodoc/mine/html/scripts.prd.html
#standardstylesheet: /metanorma-mine/lib/isodoc/mine/html/
#header: /metanorma-mine/lib/isodoc/mine/html/header.html
#wordcoverpage: /metanorma-mine/lib/isodoc/mine/html/word_mine_titlepage.html
#wordintropage: /metanorma-mine/lib/isodoc/mine/html/word_mine_intro.html
#wordstylesheet: /metanorma-mine/lib/isodoc/mine/html/wordstyle.scss
pdf_stylesheet: html/mbxif.xsl
#word_bodyfont: '"Source Sans Pro","Arial",sans-serif'
#word_headerfont: '"Source Sans Pro","Arial",sans-serif'
#word_monospacefont: '"Source Code Pro",monospace'
#word_normalfontsize: "12.0pt"
#word_monospacefontsize: "11.0pt"
#word_smallerfontsize: "10.0pt"
#word_footnotefontsize: "9.0pt"
docid_template: "{{ organization_name_short }} {{ docnumeric }}"
metadata_extensions:
  - security
published_stages:
  - published
committees:
  - TC 1
relations:
  - part-of
  - translated-from
stage_abbreviations:
  draft-proposal:
  draft-development:
  draft-testing:
  draft-implementation:
  in-force:
  retired:
metadata_extensions:
 - security
 - recipient
doctypes:
 - general-guidelines
 - recommended practice
 - test suite
default_doctype: general guideline
termsdefs_titles:
  - Terms and definitions
  - Terms, definitions, symbols and abbreviated terms
  - Terms, definitions, symbols and abbreviations
  - Terms, definitions and symbls
  - Terms, definitions and abbreviations
  - Terms, definitions and abbreviated terms
symbols_titles:
  - Symbols and abbreviated terms
  - Symbols
  - Abbreviated terms
  - Abbreviations
normref_titles:
  - Normative references
bibliography_titles:
  - Bibliography
fonts_manifest:
  - Source Sans Pro
  - Source Code Pro
